export const LUCIDE_ICON_OPTIONS = [
  { name: "Waves", label: "Swimming Pool" },
  { name: "Dumbbell", label: "Gym / Fitness" },
  { name: "Car", label: "Parking" },
  { name: "ShieldCheck", label: "Security" },
  { name: "Wind", label: "Air Conditioning" },
  { name: "Wifi", label: "Wi-Fi" },
  { name: "TreeDeciduous", label: "Garden" },
  { name: "PawPrint", label: "Pet Friendly" },
  { name: "Utensils", label: "Kitchen" },
  { name: "Coffee", label: "Café / Lounge" },
  { name: "Tv", label: "Entertainment" },
  { name: "Snowflake", label: "Cold Storage" },
  { name: "Baby", label: "Nursery" },
  { name: "Key", label: "Private Access" },
  { name: "Camera", label: "CCTV" },
  { name: "Eye", label: "Concierge" },
  { name: "Bath", label: "Bathtub / Jacuzzi" },
  { name: "Sun", label: "Rooftop / Balcony" },
  { name: "Bike", label: "Bicycle Storage" },
  { name: "ShoppingBag", label: "Shopping Nearby" },
  { name: "Stethoscope", label: "Medical / Hospital" },
  { name: "School", label: "School Nearby" },
  { name: "Zap", label: "EV Charging" },
  { name: "Droplets", label: "Water Supply" },
  { name: "Flame", label: "Fireplace" },
  { name: "Wrench", label: "Maintenance" },
  { name: "Star", label: "Premium Feature" },
  { name: "Check", label: "Included" },
  { name: "Building2", label: "High Rise" },
  { name: "Home", label: "Private Garden" },
  { name: "Lock", label: "Smart Lock" },
  { name: "Maximize2", label: "Large Space" },
  { name: "Sailboat", label: "Water Sports" },
  { name: "Trees", label: "Green Area" },
  { name: "PackageOpen", label: "Storage Room" },
] as const;

export type LucideIconName = (typeof LUCIDE_ICON_OPTIONS)[number]["name"];
