export const TRANSIT_LINES = [
  "BTS_SUKHUMVIT",
  "BTS_SILOM",
  "BTS_GOLD",
  "MRT_BLUE",
  "MRT_PURPLE",
  "MRT_YELLOW",
  "MRT_PINK",
  "ARL",
  "SRT_RED",
  "BRT",
] as const;

export type TransitLine = (typeof TRANSIT_LINES)[number];

export const TRANSIT_LINE_LABELS: Record<TransitLine, string> = {
  BTS_SUKHUMVIT: "BTS Sukhumvit Line",
  BTS_SILOM: "BTS Silom Line",
  BTS_GOLD: "BTS Gold Line",
  MRT_BLUE: "MRT Blue Line",
  MRT_PURPLE: "MRT Purple Line",
  MRT_YELLOW: "MRT Yellow Line",
  MRT_PINK: "MRT Pink Line",
  ARL: "Airport Rail Link",
  SRT_RED: "SRT Red Line",
  BRT: "BRT",
};

export const TRANSIT_LINE_COLORS: Record<TransitLine, string> = {
  BTS_SUKHUMVIT: "#63B140",
  BTS_SILOM: "#006450",
  BTS_GOLD: "#D4AF37",
  MRT_BLUE: "#193175",
  MRT_PURPLE: "#712D92",
  MRT_YELLOW: "#F9DF00",
  MRT_PINK: "#F1A5C2",
  ARL: "#982639",
  SRT_RED: "#901414",
  BRT: "#FF6B35",
};

export const TRANSIT_STATION_PRESETS: { code: string; name: string; slug: string; line: TransitLine }[] = [
  { code: "N24", name: "Khu Khot", slug: "n24", line: "BTS_SUKHUMVIT" },
  { code: "N23", name: "Yaek Kor Por Aor", slug: "n23", line: "BTS_SUKHUMVIT" },
  { code: "N22", name: "Royal Thai Air Force Museum", slug: "n22", line: "BTS_SUKHUMVIT" },
  { code: "N21", name: "Bhumibol Adulyadej Hospital", slug: "n21", line: "BTS_SUKHUMVIT" },
  { code: "N20", name: "Saphan Mai", slug: "n20", line: "BTS_SUKHUMVIT" },
  { code: "N19", name: "Sai Yud", slug: "n19", line: "BTS_SUKHUMVIT" },
  { code: "N18", name: "Phahon Yothin 59", slug: "n18", line: "BTS_SUKHUMVIT" },
  { code: "N17", name: "Wat Phra Sri Mahathat", slug: "n17", line: "BTS_SUKHUMVIT" },
  { code: "N16", name: "11th Infantry Regiment", slug: "n16", line: "BTS_SUKHUMVIT" },
  { code: "N15", name: "Bang Bua", slug: "n15", line: "BTS_SUKHUMVIT" },
  { code: "N14", name: "Royal Forest Department", slug: "n14", line: "BTS_SUKHUMVIT" },
  { code: "N13", name: "Kasetsart University", slug: "n13", line: "BTS_SUKHUMVIT" },
  { code: "N12", name: "Sena Nikhom", slug: "n12", line: "BTS_SUKHUMVIT" },
  { code: "N11", name: "Ratchayothin", slug: "n11", line: "BTS_SUKHUMVIT" },
  { code: "N10", name: "Phahon Yothin 24", slug: "n10", line: "BTS_SUKHUMVIT" },
  { code: "N09", name: "Ha Yaek Lat Phrao", slug: "n09", line: "BTS_SUKHUMVIT" },
  { code: "N08", name: "Mo Chit", slug: "n08", line: "BTS_SUKHUMVIT" },
  { code: "N07", name: "Saphan Khwai", slug: "n07", line: "BTS_SUKHUMVIT" },
  { code: "N05", name: "Ari", slug: "n05", line: "BTS_SUKHUMVIT" },
  { code: "N04", name: "Sanam Pao", slug: "n04", line: "BTS_SUKHUMVIT" },
  { code: "N03", name: "Victory Monument", slug: "n03", line: "BTS_SUKHUMVIT" },
  { code: "N02", name: "Phaya Thai", slug: "n02", line: "BTS_SUKHUMVIT" },
  { code: "N01", name: "Ratchathewi", slug: "n01", line: "BTS_SUKHUMVIT" },
  { code: "CEN-S", name: "Siam (Sukhumvit)", slug: "cen-s", line: "BTS_SUKHUMVIT" },
  { code: "E01", name: "Chit Lom", slug: "e01", line: "BTS_SUKHUMVIT" },
  { code: "E02", name: "Phloen Chit", slug: "e02", line: "BTS_SUKHUMVIT" },
  { code: "E03", name: "Nana", slug: "e03", line: "BTS_SUKHUMVIT" },
  { code: "E04", name: "Asok", slug: "e04", line: "BTS_SUKHUMVIT" },
  { code: "E05", name: "Phrom Phong", slug: "e05", line: "BTS_SUKHUMVIT" },
  { code: "E06", name: "Thong Lo", slug: "e06", line: "BTS_SUKHUMVIT" },
  { code: "E07", name: "Ekkamai", slug: "e07", line: "BTS_SUKHUMVIT" },
  { code: "E08", name: "Phra Khanong", slug: "e08", line: "BTS_SUKHUMVIT" },
  { code: "E09", name: "On Nut", slug: "e09", line: "BTS_SUKHUMVIT" },
  { code: "E10", name: "Bang Chak", slug: "e10", line: "BTS_SUKHUMVIT" },
  { code: "E11", name: "Punnawithi", slug: "e11", line: "BTS_SUKHUMVIT" },
  { code: "E12", name: "Udom Suk", slug: "e12", line: "BTS_SUKHUMVIT" },
  { code: "E13", name: "Bang Na", slug: "e13", line: "BTS_SUKHUMVIT" },
  { code: "E14", name: "Bearing", slug: "e14", line: "BTS_SUKHUMVIT" },
  { code: "E15", name: "Samrong", slug: "e15", line: "BTS_SUKHUMVIT" },
  { code: "E16", name: "Pu Chao", slug: "e16", line: "BTS_SUKHUMVIT" },
  { code: "E17", name: "Chang Erawan", slug: "e17", line: "BTS_SUKHUMVIT" },
  { code: "E18", name: "Royal Thai Naval Academy", slug: "e18", line: "BTS_SUKHUMVIT" },
  { code: "E19", name: "Pak Nam", slug: "e19", line: "BTS_SUKHUMVIT" },
  { code: "E20", name: "Srinagarindra", slug: "e20", line: "BTS_SUKHUMVIT" },
  { code: "E21", name: "Phraek Sa", slug: "e21", line: "BTS_SUKHUMVIT" },
  { code: "E22", name: "Sai Luat", slug: "e22", line: "BTS_SUKHUMVIT" },
  { code: "E23", name: "Kheha", slug: "e23", line: "BTS_SUKHUMVIT" },

  { code: "W01", name: "National Stadium", slug: "w01", line: "BTS_SILOM" },
  { code: "CEN-SL", name: "Siam (Silom)", slug: "cen-sl", line: "BTS_SILOM" },
  { code: "S01", name: "Ratchadamri", slug: "s01", line: "BTS_SILOM" },
  { code: "S02", name: "Sala Daeng", slug: "s02", line: "BTS_SILOM" },
  { code: "S03", name: "Chong Nonsi", slug: "s03", line: "BTS_SILOM" },
  { code: "S04", name: "Saint Louis", slug: "s04", line: "BTS_SILOM" },
  { code: "S05", name: "Surasak", slug: "s05", line: "BTS_SILOM" },
  { code: "S06", name: "Saphan Taksin", slug: "s06", line: "BTS_SILOM" },
  { code: "S07", name: "Krung Thon Buri", slug: "s07", line: "BTS_SILOM" },
  { code: "S08", name: "Wongwian Yai", slug: "s08", line: "BTS_SILOM" },
  { code: "S09", name: "Pho Nimit", slug: "s09", line: "BTS_SILOM" },
  { code: "S10", name: "Talat Phlu", slug: "s10", line: "BTS_SILOM" },
  { code: "S11", name: "Wutthakat", slug: "s11", line: "BTS_SILOM" },
  { code: "S12", name: "Bang Wa", slug: "s12", line: "BTS_SILOM" },

  { code: "G01", name: "Krung Thon Buri (Gold)", slug: "g01", line: "BTS_GOLD" },
  { code: "G02", name: "Charoen Nakhon", slug: "g02", line: "BTS_GOLD" },
  { code: "G03", name: "Khlong San", slug: "g03", line: "BTS_GOLD" },

  { code: "BL01", name: "Tha Phra", slug: "bl01", line: "MRT_BLUE" },
  { code: "BL02", name: "Charan 13", slug: "bl02", line: "MRT_BLUE" },
  { code: "BL03", name: "Fai Chai", slug: "bl03", line: "MRT_BLUE" },
  { code: "BL04", name: "Bang Khun Non", slug: "bl04", line: "MRT_BLUE" },
  { code: "BL05", name: "Bang Yi Khan", slug: "bl05", line: "MRT_BLUE" },
  { code: "BL06", name: "Sirindhorn", slug: "bl06", line: "MRT_BLUE" },
  { code: "BL07", name: "Bang Phlat", slug: "bl07", line: "MRT_BLUE" },
  { code: "BL08", name: "Bang O", slug: "bl08", line: "MRT_BLUE" },
  { code: "BL09", name: "Bang Pho", slug: "bl09", line: "MRT_BLUE" },
  { code: "BL10", name: "Tao Poon", slug: "bl10", line: "MRT_BLUE" },
  { code: "BL11", name: "Bang Sue", slug: "bl11", line: "MRT_BLUE" },
  { code: "BL12", name: "Kamphaeng Phet", slug: "bl12", line: "MRT_BLUE" },
  { code: "BL13", name: "Chatuchak Park", slug: "bl13", line: "MRT_BLUE" },
  { code: "BL14", name: "Phahon Yothin", slug: "bl14", line: "MRT_BLUE" },
  { code: "BL15", name: "Lat Phrao (Blue)", slug: "bl15", line: "MRT_BLUE" },
  { code: "BL16", name: "Ratchadaphisek", slug: "bl16", line: "MRT_BLUE" },
  { code: "BL17", name: "Sutthisan", slug: "bl17", line: "MRT_BLUE" },
  { code: "BL18", name: "Huai Khwang", slug: "bl18", line: "MRT_BLUE" },
  { code: "BL19", name: "Thailand Cultural Centre", slug: "bl19", line: "MRT_BLUE" },
  { code: "BL20", name: "Phra Ram 9", slug: "bl20", line: "MRT_BLUE" },
  { code: "BL21", name: "Phetchaburi", slug: "bl21", line: "MRT_BLUE" },
  { code: "BL22", name: "Sukhumvit (MRT)", slug: "bl22", line: "MRT_BLUE" },
  { code: "BL23", name: "Queen Sirikit National Convention Centre", slug: "bl23", line: "MRT_BLUE" },
  { code: "BL24", name: "Khlong Toei", slug: "bl24", line: "MRT_BLUE" },
  { code: "BL25", name: "Lumphini", slug: "bl25", line: "MRT_BLUE" },
  { code: "BL26", name: "Si Lom", slug: "bl26", line: "MRT_BLUE" },
  { code: "BL27", name: "Sam Yan", slug: "bl27", line: "MRT_BLUE" },
  { code: "BL28", name: "Hua Lamphong", slug: "bl28", line: "MRT_BLUE" },
  { code: "BL29", name: "Wat Mangkon", slug: "bl29", line: "MRT_BLUE" },
  { code: "BL30", name: "Sam Yot", slug: "bl30", line: "MRT_BLUE" },
  { code: "BL31", name: "Sanam Chai", slug: "bl31", line: "MRT_BLUE" },
  { code: "BL32", name: "Itsaraphap", slug: "bl32", line: "MRT_BLUE" },
  { code: "BL33", name: "Bang Phai", slug: "bl33", line: "MRT_BLUE" },
  { code: "BL34", name: "Bang Wa (Blue)", slug: "bl34", line: "MRT_BLUE" },
  { code: "BL35", name: "Phetkasem 48", slug: "bl35", line: "MRT_BLUE" },
  { code: "BL36", name: "Phasi Charoen", slug: "bl36", line: "MRT_BLUE" },
  { code: "BL37", name: "Bang Khae", slug: "bl37", line: "MRT_BLUE" },
  { code: "BL38", name: "Lak Song", slug: "bl38", line: "MRT_BLUE" },

  { code: "PP01", name: "Khlong Bang Phai", slug: "pp01", line: "MRT_PURPLE" },
  { code: "PP02", name: "Talad Bang Yai", slug: "pp02", line: "MRT_PURPLE" },
  { code: "PP03", name: "Sam Yaek Bang Yai", slug: "pp03", line: "MRT_PURPLE" },
  { code: "PP04", name: "Bang Phlo", slug: "pp04", line: "MRT_PURPLE" },
  { code: "PP05", name: "Bang Rak Yai", slug: "pp05", line: "MRT_PURPLE" },
  { code: "PP06", name: "Bang Rak Noi Tha It", slug: "pp06", line: "MRT_PURPLE" },
  { code: "PP07", name: "Sai Ma", slug: "pp07", line: "MRT_PURPLE" },
  { code: "PP08", name: "Phra Nang Klao Bridge", slug: "pp08", line: "MRT_PURPLE" },
  { code: "PP09", name: "Yaek Nonthaburi 1", slug: "pp09", line: "MRT_PURPLE" },
  { code: "PP10", name: "Bang Krasor", slug: "pp10", line: "MRT_PURPLE" },
  { code: "PP11", name: "Nonthaburi Civic Center", slug: "pp11", line: "MRT_PURPLE" },
  { code: "PP12", name: "Ministry of Public Health", slug: "pp12", line: "MRT_PURPLE" },
  { code: "PP13", name: "Yaek Tiwanon", slug: "pp13", line: "MRT_PURPLE" },
  { code: "PP14", name: "Wong Sawang", slug: "pp14", line: "MRT_PURPLE" },
  { code: "PP15", name: "Bang Son", slug: "pp15", line: "MRT_PURPLE" },
  { code: "PP16", name: "Tao Poon (Purple)", slug: "pp16", line: "MRT_PURPLE" },

  { code: "YL01", name: "Lat Phrao (Yellow)", slug: "yl01", line: "MRT_YELLOW" },
  { code: "YL02", name: "Phawana", slug: "yl02", line: "MRT_YELLOW" },
  { code: "YL03", name: "Chok Chai 4", slug: "yl03", line: "MRT_YELLOW" },
  { code: "YL04", name: "Lat Phrao 71", slug: "yl04", line: "MRT_YELLOW" },
  { code: "YL05", name: "Lat Phrao 83", slug: "yl05", line: "MRT_YELLOW" },
  { code: "YL06", name: "Mahai Thai", slug: "yl06", line: "MRT_YELLOW" },
  { code: "YL07", name: "Lat Phrao 101", slug: "yl07", line: "MRT_YELLOW" },
  { code: "YL08", name: "Bang Kapi", slug: "yl08", line: "MRT_YELLOW" },
  { code: "YL09", name: "Yaek Lam Sali", slug: "yl09", line: "MRT_YELLOW" },
  { code: "YL10", name: "Si Kritha", slug: "yl10", line: "MRT_YELLOW" },
  { code: "YL11", name: "Hua Mak (Yellow)", slug: "yl11", line: "MRT_YELLOW" },
  { code: "YL12", name: "Kalantan", slug: "yl12", line: "MRT_YELLOW" },
  { code: "YL13", name: "Si Nut", slug: "yl13", line: "MRT_YELLOW" },
  { code: "YL14", name: "Srinagarindra 38", slug: "yl14", line: "MRT_YELLOW" },
  { code: "YL15", name: "Suan Luang Rama IX", slug: "yl15", line: "MRT_YELLOW" },
  { code: "YL16", name: "Si Iam", slug: "yl16", line: "MRT_YELLOW" },
  { code: "YL17", name: "Si Udom", slug: "yl17", line: "MRT_YELLOW" },
  { code: "YL18", name: "Si Thepha", slug: "yl18", line: "MRT_YELLOW" },
  { code: "YL19", name: "Si La Salle", slug: "yl19", line: "MRT_YELLOW" },
  { code: "YL20", name: "Si Bearing", slug: "yl20", line: "MRT_YELLOW" },
  { code: "YL21", name: "Si Dan", slug: "yl21", line: "MRT_YELLOW" },
  { code: "YL22", name: "Si Pu Chao", slug: "yl22", line: "MRT_YELLOW" },
  { code: "YL23", name: "Si Samrong", slug: "yl23", line: "MRT_YELLOW" },

  { code: "PK01", name: "Nonthaburi Civic Center (Pink)", slug: "pk01", line: "MRT_PINK" },
  { code: "PK02", name: "Khae Rai", slug: "pk02", line: "MRT_PINK" },
  { code: "PK03", name: "Sanambin Nam", slug: "pk03", line: "MRT_PINK" },
  { code: "PK04", name: "Royal Irrigation Department", slug: "pk04", line: "MRT_PINK" },
  { code: "PK05", name: "Muang Thong Thani", slug: "pk05", line: "MRT_PINK" },
  { code: "PK06", name: "Chaeng Watthana 14", slug: "pk06", line: "MRT_PINK" },
  { code: "PK07", name: "Government Complex", slug: "pk07", line: "MRT_PINK" },
  { code: "PK08", name: "Chaeng Watthana-Pak Kret 28", slug: "pk08", line: "MRT_PINK" },
  { code: "PK09", name: "Pak Kret", slug: "pk09", line: "MRT_PINK" },
  { code: "PK10", name: "Sri Rat", slug: "pk10", line: "MRT_PINK" },
  { code: "PK11", name: "Sri Sawat", slug: "pk11", line: "MRT_PINK" },
  { code: "PK12", name: "Sri Udom", slug: "pk12", line: "MRT_PINK" },
  { code: "PK13", name: "Sri Thepha (Pink)", slug: "pk13", line: "MRT_PINK" },
  { code: "PK14", name: "Sri La Salle", slug: "pk14", line: "MRT_PINK" },
  { code: "PK15", name: "Sri Bearing", slug: "pk15", line: "MRT_PINK" },
  { code: "PK16", name: "Sri Dan", slug: "pk16", line: "MRT_PINK" },
  { code: "PK17", name: "Sri Pu Chao", slug: "pk17", line: "MRT_PINK" },
  { code: "PK18", name: "Sri Samrong", slug: "pk18", line: "MRT_PINK" },
  { code: "PK19", name: "Sri Iam (Pink)", slug: "pk19", line: "MRT_PINK" },
  { code: "PK20", name: "Sri Udom (Pink)", slug: "pk20", line: "MRT_PINK" },
  { code: "PK21", name: "Sri Thepha 2", slug: "pk21", line: "MRT_PINK" },
  { code: "PK22", name: "Sri La Salle (Pink)", slug: "pk22", line: "MRT_PINK" },
  { code: "PK23", name: "Sri Bearing (Pink)", slug: "pk23", line: "MRT_PINK" },
  { code: "PK24", name: "Sri Dan (Pink)", slug: "pk24", line: "MRT_PINK" },
  { code: "PK25", name: "Sri Pu Chao (Pink)", slug: "pk25", line: "MRT_PINK" },
  { code: "PK26", name: "Sri Samrong (Pink)", slug: "pk26", line: "MRT_PINK" },

  { code: "A01", name: "Suvarnabhumi", slug: "a01", line: "ARL" },
  { code: "A02", name: "Lat Krabang", slug: "a02", line: "ARL" },
  { code: "A03", name: "Ban Thap Chang", slug: "a03", line: "ARL" },
  { code: "A04", name: "Hua Mak (ARL)", slug: "a04", line: "ARL" },
  { code: "A05", name: "Ramkhamhaeng", slug: "a05", line: "ARL" },
  { code: "A06", name: "Makkasan", slug: "a06", line: "ARL" },
  { code: "A07", name: "Ratchaprarop", slug: "a07", line: "ARL" },
  { code: "A08", name: "Phaya Thai (ARL)", slug: "a08", line: "ARL" },

  { code: "RW01", name: "Bang Sue Grand Station", slug: "rw01", line: "SRT_RED" },
  { code: "RW02", name: "Chatuchak (Red)", slug: "rw02", line: "SRT_RED" },
  { code: "RW03", name: "Wat Samian Nari", slug: "rw03", line: "SRT_RED" },
  { code: "RW04", name: "Bang Khen", slug: "rw04", line: "SRT_RED" },
  { code: "RW05", name: "Thung Song Hong", slug: "rw05", line: "SRT_RED" },
  { code: "RW06", name: "Lak Si", slug: "rw06", line: "SRT_RED" },
  { code: "RW07", name: "Kan Kheha", slug: "rw07", line: "SRT_RED" },
  { code: "RW08", name: "Don Mueang", slug: "rw08", line: "SRT_RED" },
  { code: "RW09", name: "Lak Hok", slug: "rw09", line: "SRT_RED" },
  { code: "RW10", name: "Rangsit", slug: "rw10", line: "SRT_RED" },
];
