services:
  executive-homes-app:
    build:
      context: .
      target: development
    image: waiyandev/executive-homes-app-dev:latest
    container_name: executive-homes-app
    ports:
      - "3001:3001"
    command: ["sh", "-c", "pnpm install && pnpm dev --hostname 0.0.0.0 --port 3001"]
    env_file:
      - .env.docker
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - CI=true
    volumes:
      - .:/app
      - executive_homes_node_modules:/app/node_modules
      - executive_homes_pnpm_store:/root/.pnpm-store
    depends_on:
      executive-homes-db:
        condition: service_healthy

  executive-homes-db:
    image: postgres:15-alpine
    env_file:
      - .env.docker
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    container_name: executive-homes-db
    ports:
      - "5433:5432"
    volumes:
      - executive_homes_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  executive_homes_db_data:
  executive_homes_node_modules:
  executive_homes_pnpm_store:
