import { PrismaClient } from "../generated/prisma/client";
import { type TransitLine } from "@/constants/transitStations";

const TRANSIT_STATION_DATA: { code: string; name: string; slug: string; line: TransitLine }[] = [
  { code: "N24", name: "Khu Khot BTS", slug: "n24", line: "BTS_SUKHUMVIT" },
  { code: "N23", name: "Yaek Kor Por Aor BTS", slug: "n23", line: "BTS_SUKHUMVIT" },
  { code: "N22", name: "Royal Thai Air Force Museum BTS", slug: "n22", line: "BTS_SUKHUMVIT" },
  { code: "N21", name: "Bhumibol Adulyadej Hospital BTS", slug: "n21", line: "BTS_SUKHUMVIT" },
  { code: "N20", name: "Saphan Mai BTS", slug: "n20", line: "BTS_SUKHUMVIT" },
  { code: "N19", name: "Sai Yud BTS", slug: "n19", line: "BTS_SUKHUMVIT" },
  { code: "N18", name: "Phahon Yothin 59 BTS", slug: "n18", line: "BTS_SUKHUMVIT" },
  { code: "N17", name: "Wat Phra Sri Mahathat BTS", slug: "n17", line: "BTS_SUKHUMVIT" },
  { code: "N16", name: "11th Infantry Regiment BTS", slug: "n16", line: "BTS_SUKHUMVIT" },
  { code: "N15", name: "Bang Bua BTS", slug: "n15", line: "BTS_SUKHUMVIT" },
  { code: "N14", name: "Royal Forest Department BTS", slug: "n14", line: "BTS_SUKHUMVIT" },
  { code: "N13", name: "Kasetsart University BTS", slug: "n13", line: "BTS_SUKHUMVIT" },
  { code: "N12", name: "Sena Nikhom BTS", slug: "n12", line: "BTS_SUKHUMVIT" },
  { code: "N11", name: "Ratchayothin BTS", slug: "n11", line: "BTS_SUKHUMVIT" },
  { code: "N10", name: "Phahon Yothin 24 BTS", slug: "n10", line: "BTS_SUKHUMVIT" },
  { code: "N09", name: "Ha Yaek Lat Phrao BTS", slug: "n09", line: "BTS_SUKHUMVIT" },
  { code: "N08", name: "Mo Chit BTS", slug: "n08", line: "BTS_SUKHUMVIT" },
  { code: "N07", name: "Saphan Khwai BTS", slug: "n07", line: "BTS_SUKHUMVIT" },
  { code: "N05", name: "Ari BTS", slug: "n05", line: "BTS_SUKHUMVIT" },
  { code: "N04", name: "Sanam Pao BTS", slug: "n04", line: "BTS_SUKHUMVIT" },
  { code: "N03", name: "Victory Monument BTS", slug: "n03", line: "BTS_SUKHUMVIT" },
  { code: "N02", name: "Phaya Thai BTS", slug: "n02", line: "BTS_SUKHUMVIT" },
  { code: "N01", name: "Ratchathewi BTS", slug: "n01", line: "BTS_SUKHUMVIT" },
  { code: "CEN-S", name: "Siam BTS", slug: "cen-s", line: "BTS_SUKHUMVIT" },
  { code: "E01", name: "Chit Lom BTS", slug: "e01", line: "BTS_SUKHUMVIT" },
  { code: "E02", name: "Phloen Chit BTS", slug: "e02", line: "BTS_SUKHUMVIT" },
  { code: "E03", name: "Nana BTS", slug: "e03", line: "BTS_SUKHUMVIT" },
  { code: "E04", name: "Asok BTS", slug: "e04", line: "BTS_SUKHUMVIT" },
  { code: "E05", name: "Phrom Phong BTS", slug: "e05", line: "BTS_SUKHUMVIT" },
  { code: "E06", name: "Thong Lo BTS", slug: "e06", line: "BTS_SUKHUMVIT" },
  { code: "E07", name: "Ekkamai BTS", slug: "e07", line: "BTS_SUKHUMVIT" },
  { code: "E08", name: "Phra Khanong BTS", slug: "e08", line: "BTS_SUKHUMVIT" },
  { code: "E09", name: "On Nut BTS", slug: "e09", line: "BTS_SUKHUMVIT" },
  { code: "E10", name: "Bang Chak BTS", slug: "e10", line: "BTS_SUKHUMVIT" },
  { code: "E11", name: "Punnawithi BTS", slug: "e11", line: "BTS_SUKHUMVIT" },
  { code: "E12", name: "Udom Suk BTS", slug: "e12", line: "BTS_SUKHUMVIT" },
  { code: "E13", name: "Bang Na BTS", slug: "e13", line: "BTS_SUKHUMVIT" },
  { code: "E14", name: "Bearing BTS", slug: "e14", line: "BTS_SUKHUMVIT" },
  { code: "E15", name: "Samrong BTS", slug: "e15", line: "BTS_SUKHUMVIT" },
  { code: "E16", name: "Pu Chao BTS", slug: "e16", line: "BTS_SUKHUMVIT" },
  { code: "E17", name: "Chang Erawan BTS", slug: "e17", line: "BTS_SUKHUMVIT" },
  { code: "E18", name: "Royal Thai Naval Academy BTS", slug: "e18", line: "BTS_SUKHUMVIT" },
  { code: "E19", name: "Pak Nam BTS", slug: "e19", line: "BTS_SUKHUMVIT" },
  { code: "E20", name: "Srinagarindra BTS", slug: "e20", line: "BTS_SUKHUMVIT" },
  { code: "E21", name: "Phraek Sa BTS", slug: "e21", line: "BTS_SUKHUMVIT" },
  { code: "E22", name: "Sai Luat BTS", slug: "e22", line: "BTS_SUKHUMVIT" },
  { code: "E23", name: "Kheha BTS", slug: "e23", line: "BTS_SUKHUMVIT" },

  { code: "W01", name: "National Stadium BTS", slug: "w01", line: "BTS_SILOM" },
  { code: "CEN-SL", name: "Siam BTS", slug: "cen-sl", line: "BTS_SILOM" },
  { code: "S01", name: "Ratchadamri BTS", slug: "s01", line: "BTS_SILOM" },
  { code: "S02", name: "Sala Daeng BTS", slug: "s02", line: "BTS_SILOM" },
  { code: "S03", name: "Chong Nonsi BTS", slug: "s03", line: "BTS_SILOM" },
  { code: "S04", name: "Saint Louis BTS", slug: "s04", line: "BTS_SILOM" },
  { code: "S05", name: "Surasak BTS", slug: "s05", line: "BTS_SILOM" },
  { code: "S06", name: "Saphan Taksin BTS", slug: "s06", line: "BTS_SILOM" },
  { code: "S07", name: "Krung Thon Buri BTS", slug: "s07", line: "BTS_SILOM" },
  { code: "S08", name: "Wongwian Yai BTS", slug: "s08", line: "BTS_SILOM" },
  { code: "S09", name: "Pho Nimit BTS", slug: "s09", line: "BTS_SILOM" },
  { code: "S10", name: "Talat Phlu BTS", slug: "s10", line: "BTS_SILOM" },
  { code: "S11", name: "Wutthakat BTS", slug: "s11", line: "BTS_SILOM" },
  { code: "S12", name: "Bang Wa BTS", slug: "s12", line: "BTS_SILOM" },

  { code: "G01", name: "Krung Thon Buri BTS", slug: "g01", line: "BTS_GOLD" },
  { code: "G02", name: "Charoen Nakhon BTS", slug: "g02", line: "BTS_GOLD" },
  { code: "G03", name: "Khlong San BTS", slug: "g03", line: "BTS_GOLD" },

  { code: "BL01", name: "Tha Phra MRT", slug: "bl01", line: "MRT_BLUE" },
  { code: "BL02", name: "Charan 13 MRT", slug: "bl02", line: "MRT_BLUE" },
  { code: "BL03", name: "Fai Chai MRT", slug: "bl03", line: "MRT_BLUE" },
  { code: "BL04", name: "Bang Khun Non MRT", slug: "bl04", line: "MRT_BLUE" },
  { code: "BL05", name: "Bang Yi Khan MRT", slug: "bl05", line: "MRT_BLUE" },
  { code: "BL06", name: "Sirindhorn MRT", slug: "bl06", line: "MRT_BLUE" },
  { code: "BL07", name: "Bang Phlat MRT", slug: "bl07", line: "MRT_BLUE" },
  { code: "BL08", name: "Bang O MRT", slug: "bl08", line: "MRT_BLUE" },
  { code: "BL09", name: "Bang Pho MRT", slug: "bl09", line: "MRT_BLUE" },
  { code: "BL10", name: "Tao Poon MRT", slug: "bl10", line: "MRT_BLUE" },
  { code: "BL11", name: "Bang Sue MRT", slug: "bl11", line: "MRT_BLUE" },
  { code: "BL12", name: "Kamphaeng Phet MRT", slug: "bl12", line: "MRT_BLUE" },
  { code: "BL13", name: "Chatuchak Park MRT", slug: "bl13", line: "MRT_BLUE" },
  { code: "BL14", name: "Phahon Yothin MRT", slug: "bl14", line: "MRT_BLUE" },
  { code: "BL15", name: "Lat Phrao MRT", slug: "bl15", line: "MRT_BLUE" },
  { code: "BL16", name: "Ratchadaphisek MRT", slug: "bl16", line: "MRT_BLUE" },
  { code: "BL17", name: "Sutthisan MRT", slug: "bl17", line: "MRT_BLUE" },
  { code: "BL18", name: "Huai Khwang MRT", slug: "bl18", line: "MRT_BLUE" },
  { code: "BL19", name: "Thailand Cultural Centre MRT", slug: "bl19", line: "MRT_BLUE" },
  { code: "BL20", name: "Phra Ram 9 MRT", slug: "bl20", line: "MRT_BLUE" },
  { code: "BL21", name: "Phetchaburi MRT", slug: "bl21", line: "MRT_BLUE" },
  { code: "BL22", name: "Sukhumvit MRT", slug: "bl22", line: "MRT_BLUE" },
  { code: "BL23", name: "Queen Sirikit National Convention Centre MRT", slug: "bl23", line: "MRT_BLUE" },
  { code: "BL24", name: "Khlong Toei MRT", slug: "bl24", line: "MRT_BLUE" },
  { code: "BL25", name: "Lumphini MRT", slug: "bl25", line: "MRT_BLUE" },
  { code: "BL26", name: "Si Lom MRT", slug: "bl26", line: "MRT_BLUE" },
  { code: "BL27", name: "Sam Yan MRT", slug: "bl27", line: "MRT_BLUE" },
  { code: "BL28", name: "Hua Lamphong MRT", slug: "bl28", line: "MRT_BLUE" },
  { code: "BL29", name: "Wat Mangkon MRT", slug: "bl29", line: "MRT_BLUE" },
  { code: "BL30", name: "Sam Yot MRT", slug: "bl30", line: "MRT_BLUE" },
  { code: "BL31", name: "Sanam Chai MRT", slug: "bl31", line: "MRT_BLUE" },
  { code: "BL32", name: "Itsaraphap MRT", slug: "bl32", line: "MRT_BLUE" },
  { code: "BL33", name: "Bang Phai MRT", slug: "bl33", line: "MRT_BLUE" },
  { code: "BL34", name: "Bang Wa MRT", slug: "bl34", line: "MRT_BLUE" },
  { code: "BL35", name: "Phetkasem 48 MRT", slug: "bl35", line: "MRT_BLUE" },
  { code: "BL36", name: "Phasi Charoen MRT", slug: "bl36", line: "MRT_BLUE" },
  { code: "BL37", name: "Bang Khae MRT", slug: "bl37", line: "MRT_BLUE" },
  { code: "BL38", name: "Lak Song MRT", slug: "bl38", line: "MRT_BLUE" },

  { code: "PP01", name: "Khlong Bang Phai MRT", slug: "pp01", line: "MRT_PURPLE" },
  { code: "PP02", name: "Talad Bang Yai MRT", slug: "pp02", line: "MRT_PURPLE" },
  { code: "PP03", name: "Sam Yaek Bang Yai MRT", slug: "pp03", line: "MRT_PURPLE" },
  { code: "PP04", name: "Bang Phlo MRT", slug: "pp04", line: "MRT_PURPLE" },
  { code: "PP05", name: "Bang Rak Yai MRT", slug: "pp05", line: "MRT_PURPLE" },
  { code: "PP06", name: "Bang Rak Noi Tha It MRT", slug: "pp06", line: "MRT_PURPLE" },
  { code: "PP07", name: "Sai Ma MRT", slug: "pp07", line: "MRT_PURPLE" },
  { code: "PP08", name: "Phra Nang Klao Bridge MRT", slug: "pp08", line: "MRT_PURPLE" },
  { code: "PP09", name: "Yaek Nonthaburi 1 MRT", slug: "pp09", line: "MRT_PURPLE" },
  { code: "PP10", name: "Bang Krasor MRT", slug: "pp10", line: "MRT_PURPLE" },
  { code: "PP11", name: "Nonthaburi Civic Center MRT", slug: "pp11", line: "MRT_PURPLE" },
  { code: "PP12", name: "Ministry of Public Health MRT", slug: "pp12", line: "MRT_PURPLE" },
  { code: "PP13", name: "Yaek Tiwanon MRT", slug: "pp13", line: "MRT_PURPLE" },
  { code: "PP14", name: "Wong Sawang MRT", slug: "pp14", line: "MRT_PURPLE" },
  { code: "PP15", name: "Bang Son MRT", slug: "pp15", line: "MRT_PURPLE" },
  { code: "PP16", name: "Tao Poon MRT", slug: "pp16", line: "MRT_PURPLE" },

  { code: "YL01", name: "Lat Phrao MRT", slug: "yl01", line: "MRT_YELLOW" },
  { code: "YL02", name: "Phawana MRT", slug: "yl02", line: "MRT_YELLOW" },
  { code: "YL03", name: "Chok Chai 4 MRT", slug: "yl03", line: "MRT_YELLOW" },
  { code: "YL04", name: "Lat Phrao 71 MRT", slug: "yl04", line: "MRT_YELLOW" },
  { code: "YL05", name: "Lat Phrao 83 MRT", slug: "yl05", line: "MRT_YELLOW" },
  { code: "YL06", name: "Mahai Thai MRT", slug: "yl06", line: "MRT_YELLOW" },
  { code: "YL07", name: "Lat Phrao 101 MRT", slug: "yl07", line: "MRT_YELLOW" },
  { code: "YL08", name: "Bang Kapi MRT", slug: "yl08", line: "MRT_YELLOW" },
  { code: "YL09", name: "Yaek Lam Sali MRT", slug: "yl09", line: "MRT_YELLOW" },
  { code: "YL10", name: "Si Kritha MRT", slug: "yl10", line: "MRT_YELLOW" },
  { code: "YL11", name: "Hua Mak MRT", slug: "yl11", line: "MRT_YELLOW" },
  { code: "YL12", name: "Kalantan MRT", slug: "yl12", line: "MRT_YELLOW" },
  { code: "YL13", name: "Si Nut MRT", slug: "yl13", line: "MRT_YELLOW" },
  { code: "YL14", name: "Srinagarindra 38 MRT", slug: "yl14", line: "MRT_YELLOW" },
  { code: "YL15", name: "Suan Luang Rama IX MRT", slug: "yl15", line: "MRT_YELLOW" },
  { code: "YL16", name: "Si Iam MRT", slug: "yl16", line: "MRT_YELLOW" },
  { code: "YL17", name: "Si Udom MRT", slug: "yl17", line: "MRT_YELLOW" },
  { code: "YL18", name: "Si Thepha MRT", slug: "yl18", line: "MRT_YELLOW" },
  { code: "YL19", name: "Si La Salle MRT", slug: "yl19", line: "MRT_YELLOW" },
  { code: "YL20", name: "Si Bearing MRT", slug: "yl20", line: "MRT_YELLOW" },
  { code: "YL21", name: "Si Dan MRT", slug: "yl21", line: "MRT_YELLOW" },
  { code: "YL22", name: "Si Pu Chao MRT", slug: "yl22", line: "MRT_YELLOW" },
  { code: "YL23", name: "Si Samrong MRT", slug: "yl23", line: "MRT_YELLOW" },

  { code: "PK01", name: "Nonthaburi Civic Center MRT", slug: "pk01", line: "MRT_PINK" },
  { code: "PK02", name: "Khae Rai MRT", slug: "pk02", line: "MRT_PINK" },
  { code: "PK03", name: "Sanambin Nam MRT", slug: "pk03", line: "MRT_PINK" },
  { code: "PK04", name: "Royal Irrigation Department MRT", slug: "pk04", line: "MRT_PINK" },
  { code: "PK05", name: "Muang Thong Thani MRT", slug: "pk05", line: "MRT_PINK" },
  { code: "PK06", name: "Chaeng Watthana 14 MRT", slug: "pk06", line: "MRT_PINK" },
  { code: "PK07", name: "Government Complex MRT", slug: "pk07", line: "MRT_PINK" },
  { code: "PK08", name: "Chaeng Watthana-Pak Kret 28 MRT", slug: "pk08", line: "MRT_PINK" },
  { code: "PK09", name: "Pak Kret MRT", slug: "pk09", line: "MRT_PINK" },
  { code: "PK10", name: "Sri Rat MRT", slug: "pk10", line: "MRT_PINK" },
  { code: "PK11", name: "Sri Sawat MRT", slug: "pk11", line: "MRT_PINK" },
  { code: "PK12", name: "Sri Udom MRT", slug: "pk12", line: "MRT_PINK" },
  { code: "PK13", name: "Sri Thepha MRT", slug: "pk13", line: "MRT_PINK" },
  { code: "PK14", name: "Sri La Salle MRT", slug: "pk14", line: "MRT_PINK" },
  { code: "PK15", name: "Sri Bearing MRT", slug: "pk15", line: "MRT_PINK" },
  { code: "PK16", name: "Sri Dan MRT", slug: "pk16", line: "MRT_PINK" },
  { code: "PK17", name: "Sri Pu Chao MRT", slug: "pk17", line: "MRT_PINK" },
  { code: "PK18", name: "Sri Samrong MRT", slug: "pk18", line: "MRT_PINK" },
  { code: "PK19", name: "Sri Iam MRT", slug: "pk19", line: "MRT_PINK" },
  { code: "PK20", name: "Sri Udom MRT", slug: "pk20", line: "MRT_PINK" },
  { code: "PK21", name: "Sri Thepha 2 MRT", slug: "pk21", line: "MRT_PINK" },
  { code: "PK22", name: "Sri La Salle MRT", slug: "pk22", line: "MRT_PINK" },
  { code: "PK23", name: "Sri Bearing MRT", slug: "pk23", line: "MRT_PINK" },
  { code: "PK24", name: "Sri Dan MRT", slug: "pk24", line: "MRT_PINK" },
  { code: "PK25", name: "Sri Pu Chao MRT", slug: "pk25", line: "MRT_PINK" },
  { code: "PK26", name: "Sri Samrong MRT", slug: "pk26", line: "MRT_PINK" },

  { code: "A01", name: "Suvarnabhumi ARL", slug: "a01", line: "ARL" },
  { code: "A02", name: "Lat Krabang ARL", slug: "a02", line: "ARL" },
  { code: "A03", name: "Ban Thap Chang ARL", slug: "a03", line: "ARL" },
  { code: "A04", name: "Hua Mak ARL", slug: "a04", line: "ARL" },
  { code: "A05", name: "Ramkhamhaeng ARL", slug: "a05", line: "ARL" },
  { code: "A06", name: "Makkasan ARL", slug: "a06", line: "ARL" },
  { code: "A07", name: "Ratchaprarop ARL", slug: "a07", line: "ARL" },
  { code: "A08", name: "Phaya Thai ARL", slug: "a08", line: "ARL" },

  { code: "RW01", name: "Bang Sue Grand Station SRT", slug: "rw01", line: "SRT_RED" },
  { code: "RW02", name: "Chatuchak SRT", slug: "rw02", line: "SRT_RED" },
  { code: "RW03", name: "Wat Samian Nari SRT", slug: "rw03", line: "SRT_RED" },
  { code: "RW04", name: "Bang Khen SRT", slug: "rw04", line: "SRT_RED" },
  { code: "RW05", name: "Thung Song Hong SRT", slug: "rw05", line: "SRT_RED" },
  { code: "RW06", name: "Lak Si SRT", slug: "rw06", line: "SRT_RED" },
  { code: "RW07", name: "Kan Kheha SRT", slug: "rw07", line: "SRT_RED" },
  { code: "RW08", name: "Don Mueang SRT", slug: "rw08", line: "SRT_RED" },
  { code: "RW09", name: "Lak Hok SRT", slug: "rw09", line: "SRT_RED" },
  { code: "RW10", name: "Rangsit SRT", slug: "rw10", line: "SRT_RED" },
];

export async function seedTransitStations(prisma: PrismaClient) {
  console.log("Seeding transit stations...");

  for (const s of TRANSIT_STATION_DATA) {
    await prisma.transitStation.upsert({
      where: { slug: s.slug },
      update: { name: s.name },
      create: s,
    });
  }
}
