name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |


            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

            node -v
            pnpm -v

            PROJECT_DIR="/var/www/pkmovie"
            REPO_URL="git@github.com:${{ github.repository }}.git"

            if [ ! -d "$PROJECT_DIR/.git" ]; then
              echo "Repository not found or .git missing. Cloning..."
              rm -rf $PROJECT_DIR
              git clone $REPO_URL $PROJECT_DIR
            fi

            cd $PROJECT_DIR

            git reset --hard origin/main

            # Pull latest code
            git pull origin main

            # Install dependencies
            pnpm install --frozen-lockfile

            # Generate Prisma client
            pnpm run db:generate
            
            # Create .env file 
            echo "${{ secrets.DOTENV_FILE }}" > .env

            # Load env and build
            set -a && source .env && set +a
            pnpm run build

            # Run database migrations
            pnpm run db:push

            # Restart PM2
            pm2 reload ecosystem.config.cjs --env production