name: Pk Movie Build

on:
  push:
    branches: [main]

jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e
            
            if [ ! -d "~/pkmovie-app/.git" ]; then
              echo "Repository not found. Cloning..."
              git clone https://github.com/${{ github.repository }}.git ~/pkmovie-app
              cd ~/pkmovie-app
            else
              echo "Repository exists. Fetching updates..."
              cd ~/pkmovie-app
              git fetch --all
              git reset --hard origin/main
            fi

            git checkout main
            git pull --ff-only
            
            # Create .env file
            echo "${{ secrets.DOTENV_FILE }}" > .env
            
            # Dependencies installation
            npm install --frozen-lockfile
            
            # Prisma Operations
            npx prisma generate
            npx prisma db push --accept-data-loss 
            
            # Build Application
            npm run build
            
            # PM2 Management (App Name ကို တန်းထည့်ထားသည်)
            if pm2 describe "pkmovie-app" > /dev/null; then
              pm2 reload "pkmovie-app"
            else
              pm2 start "npm" --name "pkmovie-app" -- start
            fi